// src/components/Sidebar.svelte
<script>
	import { Plus } from '@lucide/svelte';
</script>

<aside class="flex w-full max-w-xs flex-col gap-8 rounded bg-neutral-900 p-4">
	<ul class="flex items-center justify-between gap-4">
		<li><a href="/"><img src="/favicon.ico" alt="icon" class="size-8" /></a></li>
		<li>
			<button
				class="inline-flex cursor-pointer rounded-full bg-emerald-800 p-2 text-emerald-400 transition-transform duration-300 hover:scale-90"
			>
				<Plus class="size-4" />
			</button>
		</li>
	</ul>
	<div class="flex-1"></div>
</aside>

// src/app/components/Sidebar.tsx
import Link from "next/link";
import AddTask from "./AddTask";
import Profile from "./Profile";

export default function Sidebar() {
  return (
    <aside className="flex w-full max-w-xs flex-col justify-between gap-8 rounded-md bg-neutral-900/60 p-4">
      <Link
        href={"/"}
        className="w-fit transition-transform duration-300 hover:scale-110"
      >
        <img src="../favicon.ico" alt="logo" className="size-8" />
      </Link>
      <ul className="flex flex-col gap-2">
        <li>
          <AddTask />
        </li>
        <li>
          <Profile />
        </li>
      </ul>
    </aside>
  );
}
